<?php

namespace ContainerWmNAYcR;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_GZcdjUjService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.gZcdjUj' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.gZcdjUj'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'App\\Controller\\ActorController::getActorByIdAction' => ['privates', '.service_locator.ZUwwaRD', 'get_ServiceLocator_ZUwwaRDService', true],
            'App\\Controller\\ActorController::homeAction' => ['privates', '.service_locator.ZUwwaRD', 'get_ServiceLocator_ZUwwaRDService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\ActorController:getActorByIdAction' => ['privates', '.service_locator.ZUwwaRD', 'get_ServiceLocator_ZUwwaRDService', true],
            'App\\Controller\\ActorController:homeAction' => ['privates', '.service_locator.ZUwwaRD', 'get_ServiceLocator_ZUwwaRDService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\ActorController::getActorByIdAction' => '?',
            'App\\Controller\\ActorController::homeAction' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\ActorController:getActorByIdAction' => '?',
            'App\\Controller\\ActorController:homeAction' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
