<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWmNAYcR\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWmNAYcR/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWmNAYcR.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWmNAYcR\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerWmNAYcR\App_KernelDevDebugContainer([
    'container.build_hash' => 'WmNAYcR',
    'container.build_id' => '7fd65a95',
    'container.build_time' => 1691390978,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWmNAYcR');
