<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'home' => [[], ['_controller' => 'App\\Controller\\ActorController::homeAction'], [], [['text', '/']], [], [], []],
    'actors' => [[], ['_controller' => 'App\\Controller\\ActorController::actors'], [], [['text', '/actors']], [], [], []],
    'actor' => [['id'], ['_controller' => 'App\\Controller\\ActorController::getActorByIdAction'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/actor']], [], [], []],
    'search_movie' => [[], ['_controller' => 'App\\Controller\\SearchController::searchMovie'], [], [['text', '/search/movie']], [], [], []],
    'genre' => [['serie'], ['serie' => null, '_controller' => 'App\\Controller\\TitleController::fetchAllGenreAction'], [], [['variable', '/', '[^/]++', 'serie', true], ['text', '/genres']], [], [], []],
    'series' => [[], ['_controller' => 'App\\Controller\\TitleController::getSeriesAction'], [], [['text', '/series']], [], [], []],
    'films' => [['genre'], ['_controller' => 'App\\Controller\\TitleController::getFilmsByGenreAction'], [], [['variable', '/', '[^/]++', 'genre', true], ['text', '/films']], [], [], []],
];
